apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ztoperator
  name: ztoperator
  namespace: ztoperator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ztoperator
subjects:
  - kind: ServiceAccount
    name: ztoperator
    namespace: ztoperator-system