name: Update API-docs

on:
  push:
    branches:
      - main
    paths:
      - 'config/crd/**'

jobs:
  run-crdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: ztoperator

      - name: Run crdoc Docker container
        run: |
          sudo docker run -u $(id -u):$(id -g) --rm -v $PWD:/workdir ghcr.io/fybrik/crdoc:latest --resources /workdir/ztoperator/config/crd --output /workdir/api-docs.md --template /workdir/ztoperator/.github/crdoc.tmpl